"""Generate include/config_portal_html.h from web/config/index.html (minified + gzip)."""

import gzip
import os
import re

try:
    Import = __import__("SCons.Script", fromlist=["Import"]).Import
    Import("env")
    PROJECT_DIR = env["PROJECT_DIR"]
except Exception:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HTML_PATH = os.path.join(PROJECT_DIR, "web", "config", "index.html")
OUT_PATH = os.path.join(PROJECT_DIR, "include", "config_portal_html.h")


def minify_html(html: str) -> str:
    html = re.sub(r"<!--[\s\S]*?-->", "", html)
    lines = []
    for line in html.split("\n"):
        s = line.strip()
        if s:
            lines.append(s)
    return "".join(lines)


def write_byte_array(out, name: str, data: bytes, per_line: int = 16) -> None:
    out.write(f"static const uint8_t {name}[] PROGMEM = {{\n")
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        out.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    out.write("};\n")


def embed():
    if not os.path.isfile(HTML_PATH):
        print(f"embed_portal_html: missing {HTML_PATH}")
        return

    with open(HTML_PATH, "r", encoding="utf-8") as f:
        raw = f.read()

    html = minify_html(raw)
    gz = gzip.compress(html.encode("utf-8"), compresslevel=9)

    with open(OUT_PATH, "w", encoding="utf-8") as out:
        out.write("#pragma once\n")
        out.write("// Auto-generated by scripts/embed_portal_html.py — do not edit.\n")
        out.write("#include <cstddef>\n\n")
        write_byte_array(out, "CONFIG_PORTAL_HTML_GZ", gz)
        out.write(f"static const size_t CONFIG_PORTAL_HTML_GZ_LEN = {len(gz)};\n")
        out.write(f"static const size_t CONFIG_PORTAL_HTML_RAW_LEN = {len(html)};\n")

    ratio = 100 * len(gz) / max(len(raw), 1)
    print(
        f"embed_portal_html: raw={len(raw)} min={len(html)} gzip={len(gz)} "
        f"({ratio:.0f}% of raw) -> {OUT_PATH}"
    )


embed()
