#include "idfm_carousel.h"

// The build script injects these macros from `.env`. Single-line mode keeps IDFM_SLOT_COUNT at 0.
#if IDFM_SLOT_COUNT > 0
const IdfmCarouselSlot kIdfmCarouselSlots[] = {
#if IDFM_SLOT_COUNT > 0
    {IDFM_SLOT_0_MONITORING_REF, IDFM_SLOT_0_LINE_REF, IDFM_SLOT_0_LINE_CODE, IDFM_SLOT_0_LABEL, IDFM_SLOT_0_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 1
    {IDFM_SLOT_1_MONITORING_REF, IDFM_SLOT_1_LINE_REF, IDFM_SLOT_1_LINE_CODE, IDFM_SLOT_1_LABEL, IDFM_SLOT_1_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 2
    {IDFM_SLOT_2_MONITORING_REF, IDFM_SLOT_2_LINE_REF, IDFM_SLOT_2_LINE_CODE, IDFM_SLOT_2_LABEL, IDFM_SLOT_2_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 3
    {IDFM_SLOT_3_MONITORING_REF, IDFM_SLOT_3_LINE_REF, IDFM_SLOT_3_LINE_CODE, IDFM_SLOT_3_LABEL, IDFM_SLOT_3_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 4
    {IDFM_SLOT_4_MONITORING_REF, IDFM_SLOT_4_LINE_REF, IDFM_SLOT_4_LINE_CODE, IDFM_SLOT_4_LABEL, IDFM_SLOT_4_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 5
    {IDFM_SLOT_5_MONITORING_REF, IDFM_SLOT_5_LINE_REF, IDFM_SLOT_5_LINE_CODE, IDFM_SLOT_5_LABEL, IDFM_SLOT_5_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 6
    {IDFM_SLOT_6_MONITORING_REF, IDFM_SLOT_6_LINE_REF, IDFM_SLOT_6_LINE_CODE, IDFM_SLOT_6_LABEL, IDFM_SLOT_6_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 7
    {IDFM_SLOT_7_MONITORING_REF, IDFM_SLOT_7_LINE_REF, IDFM_SLOT_7_LINE_CODE, IDFM_SLOT_7_LABEL, IDFM_SLOT_7_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 8
    {IDFM_SLOT_8_MONITORING_REF, IDFM_SLOT_8_LINE_REF, IDFM_SLOT_8_LINE_CODE, IDFM_SLOT_8_LABEL, IDFM_SLOT_8_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 9
    {IDFM_SLOT_9_MONITORING_REF, IDFM_SLOT_9_LINE_REF, IDFM_SLOT_9_LINE_CODE, IDFM_SLOT_9_LABEL, IDFM_SLOT_9_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 10
    {IDFM_SLOT_10_MONITORING_REF, IDFM_SLOT_10_LINE_REF, IDFM_SLOT_10_LINE_CODE, IDFM_SLOT_10_LABEL, IDFM_SLOT_10_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 11
    {IDFM_SLOT_11_MONITORING_REF, IDFM_SLOT_11_LINE_REF, IDFM_SLOT_11_LINE_CODE, IDFM_SLOT_11_LABEL, IDFM_SLOT_11_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 12
    {IDFM_SLOT_12_MONITORING_REF, IDFM_SLOT_12_LINE_REF, IDFM_SLOT_12_LINE_CODE, IDFM_SLOT_12_LABEL, IDFM_SLOT_12_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 13
    {IDFM_SLOT_13_MONITORING_REF, IDFM_SLOT_13_LINE_REF, IDFM_SLOT_13_LINE_CODE, IDFM_SLOT_13_LABEL, IDFM_SLOT_13_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 14
    {IDFM_SLOT_14_MONITORING_REF, IDFM_SLOT_14_LINE_REF, IDFM_SLOT_14_LINE_CODE, IDFM_SLOT_14_LABEL, IDFM_SLOT_14_PREFER_THEORETICAL},
#endif
#if IDFM_SLOT_COUNT > 15
    {IDFM_SLOT_15_MONITORING_REF, IDFM_SLOT_15_LINE_REF, IDFM_SLOT_15_LINE_CODE, IDFM_SLOT_15_LABEL, IDFM_SLOT_15_PREFER_THEORETICAL},
#endif
};

const size_t kIdfmCarouselCount = sizeof(kIdfmCarouselSlots) / sizeof(kIdfmCarouselSlots[0]);
#else
const IdfmCarouselSlot kIdfmCarouselSlots[] = {{nullptr, nullptr, nullptr, nullptr}};
const size_t kIdfmCarouselCount = 0;
#endif
